index:
   path: /public/
   controller: App\Controller\DefaultController::index

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

toto:
    path: /hello/
    controller: App\Controller\GalerieController